version: '3.8'
services:
  db:
    image: postgres:16
    container_name: satellite2026-db
    environment:
      POSTGRES_DB: Satellite2026
      POSTGRES_USER: samod
      POSTGRES_PASSWORD: samodsamod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: satellite2026-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
